// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeNFsW3XCkC-6YUwBZiawdQMtgO_H5wRU',
    appId: '1:771038840318:web:a2a92fa00d2673eb39acaf',
    messagingSenderId: '771038840318',
    projectId: 'laporndan-c3333',
    authDomain: 'laporndan-c3333.firebaseapp.com',
    storageBucket: 'laporndan-c3333.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCik-mhxbl26VPvVhllj31vmBgKzpBICwY',
    appId: '1:771038840318:android:a9abddfba930159839acaf',
    messagingSenderId: '771038840318',
    projectId: 'laporndan-c3333',
    storageBucket: 'laporndan-c3333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnRLuWIAWLSQ_7LKvI0jcY6o1inurJNTM',
    appId: '1:771038840318:ios:350b1de81581bb0a39acaf',
    messagingSenderId: '771038840318',
    projectId: 'laporndan-c3333',
    storageBucket: 'laporndan-c3333.appspot.com',
    iosClientId: '771038840318-39ejiq1fpkhsjvur2vjog2npmr5p00cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnRLuWIAWLSQ_7LKvI0jcY6o1inurJNTM',
    appId: '1:771038840318:ios:350b1de81581bb0a39acaf',
    messagingSenderId: '771038840318',
    projectId: 'laporndan-c3333',
    storageBucket: 'laporndan-c3333.appspot.com',
    iosClientId: '771038840318-39ejiq1fpkhsjvur2vjog2npmr5p00cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubes',
  );
}
